const proyectos = [
    {
      titulo: "Web de inscripción",
      descripcion: "Desarrollo personalizado desde cero siguiendo diseño del cliente, de páginas web de inscripción, multilenguaje. Html, Bootstrap5 y JavaScript",
      imagen: "/images/valluatravel.png",
      enlace: "https://calm-meringue-93fa32.netlify.app/castellano.html",
      categoria: "VanillaJS",
    },
    
    {
      titulo: "Landing page Naturquinoa",
      descripcion: "Desarrollo y diseño de una landing page para la Empresa Naturquinoa, utilizando Angular, TypeScript, Bootstrap5 y modo oscuro.",
      imagen: "/images/Web_naturquinoa.webp",
      enlace: "https://proyectonaturquinoa.netlify.app/",
      categoria: "React-Angular",
    },
    {
      titulo: "Web Fundación SYEI",
      descripcion: "Desarrollo y diseño de web para la Fundación SYEI, utilizando Wordpress con Elementor. Mantenimiento y actualizaciones",
      imagen: "/images/fundacion.png",
      enlace: "https://www.saludyeducacionintegrales.org/",
      categoria: "WordPress",
    },
    {
      titulo: "Web Fitoterapia Clínica",
      descripcion: "Desarrollo y diseño de web para cliente de fitoterapia, utilizando Wordpress con Elementor. Mantenimiento y actualizaciones",
      imagen: "/images/fitoterapia.png",
      enlace: "https://fitoterapiaclinica.com/",
      categoria: "WordPress",
    },
    {
      titulo: "Aplicación notas",
      descripcion: "Aplicación clon de Keeper, usando React y Vite",
      imagen: "/images/App-notas.png",
      enlace: "https://aplicacion-notas-react.netlify.app/",
      categoria: "React-Angular",
    },
    {
      titulo: "Web de diseño y desarrollo web",
      descripcion: "Desarrollo y diseño de página web para Empresa de desarrollo y diseño web, usando Wordpress y Elementor pro.",
      imagen: "/images/Gamarraweb.png",
      enlace: "https://gamarrawebdesign.wuaze.com/",
      categoria: "WordPress",
    },
    {
      titulo: "Aplicación seguimiento pacientes",
      descripcion: "Desarrollo y diseño de aplicación para seguimiento de pacientes de clínica veterinaria, usando React y Vite, y en css Bootstrap5",
      imagen: "/images/veterinaria.webp",
      enlace: "https://veterinariareact71.netlify.app/",
      categoria: "React-Angular",
    },
    {
      titulo: "Tienda Guitarra",
      descripcion: "Web venta de guitarras, usando React y Vite.",
      imagen: "/images/guitars.png",
      enlace: "https://tienda-cart-react.netlify.app/",
      categoria: "React-Angular",
    },
    {
      titulo: "Web Asociación vecinos",
      descripcion: "Desarrollo y diseño de web para la urbanización Molino de la Hoz, usando HTML5, CSS3,Bootstrap y JavaScript",
      imagen: "/images/molino_web.webp",
      enlace: "https://molinodelahoz.netlify.app/",
      categoria: "VanillaJS",
    },
    {
      titulo: "Juego de Cartas",
      descripcion: "Desarrollo y diseño de un juego de cartas, tipo carta más alta, usando HTML5, CSS3 y JavaScript",
      imagen: "/images/juego_cartas.webp",
      enlace: "https://cardgame71.netlify.app/",
      categoria: "VanillaJS",
    },
    {
      titulo: "Rediseño web",
      descripcion: "Rediseño web para mejorar la experiencia del usuario.",
      imagen: "/images/ux_experience.jpg",
      enlace: "/Informe_Rediseño_FundacionSYEI.pdf",
      categoria: "UX",
    },
    {
      titulo: "Web bricolaje",
      descripcion: "Diseño de una web dedicada a proyectos de Bricolaje, usando Figma.",
      imagen: "/images/herramientas-de-bricolaje-848x477x80xX.webp",
      enlace: "/bricolaje.pdf",
      categoria: "UX",
    },
    {
      titulo: "App snacks en cine",
      descripcion: "Se diseña una aplicación para poder pedir comida desde el cine, usando Figma.",
      imagen: "/images/cine.webp",
      enlace: "/appcine.pdf",
      categoria: "UX",
    },
    {
      titulo: "Comida sana",
      descripcion: "Diseño de una web de comida sana, diseñada en distintos tamaños de pantalla, usando Figma.",
      imagen: "/images/comida_sana.webp",
      enlace: "/comidasana.pdf",
      categoria: "UX",
    },
    {
      titulo: "Chatbot IA Generativa",
      descripcion: "Creación de un Chatbot, que da información sobre mí.Al que se puede acceder en la esquina inferior derecha de esta web",
      imagen: "/images/chatbot.png",
      enlace: "https://portfolio-oscar-gamarra.netlify.app/",
      categoria: "IA",
    },
    {
      titulo: "Automatización gastos Personal",
      descripcion: "Creación de un flujo de automatización de gastos, usando N8N,Ollama,google sheets...",
      imagen: "/images/workflow_gastos.png",
      enlace: "/doc_gastos.pdf",
      categoria: "IA",
    },
    
  ];